### ISSUE TITLE
PHPが主体の会社になぜNestJSを導入したのか?

### ISSUE THREAD

**Issue by kouchanne** [nestjs-jp/nestjs-meetup-community-conference-2022-cfp#2]
### Twitter ID (必須)

o_kouchanne

### セッションタイトル (必須)

- [X] セッションのタイトルをイシュー件名に最大40文字程度で入力しました

### セッションのアブストラクト (最大250文字) (必須)

PHPを主に使っている会社になぜNestJSを導入したのか?
採用に至ったポイントはどこか？
実際に採用してみて分かったポイント等を交えながらお話します!

### 想定受講者の開発対象やロール・役割 (複数選択可) (必須)

Web フロントエンド開発, Web バックエンド / サーバーサイド開発

### セッションのトピック (複数選択可) (必須)

アプリケーションアーキテクチャー, 開発プロセス

### セッションのフォーマット (必須)

スライドを映しながら話す、通常セッション

**Comment by naokihaba** [comment]
[NestJS meetup Online #3](https://nest-jp.connpass.com/event/247927/)  へのセッション応募ありがとうございます！

6月27日の抽選後、運営よりご連絡します
運営によるツイートのリツイートや、あるいはご自身での宣伝・所属企業の広報による宣伝など、ぜひぜひソーシャルでのシェアもお願いいたします。

**Comment by odanado** [comment]
@kouchanne 
NestJS meetup Online #3 へのセッション応募ありがとうございました！

抽選の結果,登壇が決定しましたのでお知らせします。

今後のやり取りについては引き続きGitHubで行います

早速ですが2点確認がございます

1. 当日のリハーサルについて
当日は19時半開始ですが、19時頃に集まって登壇用のシステムの説明を行いたいと考えています。
19時から予定は空いていますか？
空いていない場合平日のどこかで時間を合わせられればと考えています

2. Compassイベントページに掲載するセッション情報について

イベント当日の1週間前までに以下を共有ください
- 所属企業（任意）
- イベントヘッダーに表示するアイコン画像（任意）
- スライドに表示する企業ロゴ画像（任意）SVGやAIファイル等

イメージは[NestJS meetup Online #2](https://nest-jp.connpass.com/event/244015/) を参照ください

**Comment by kouchanne** [comment]
@odanado 

>当日のリハーサルについて
>当日は19時半開始ですが、19時頃に集まって登壇用のシステムの説明を行いたいと考えています。
>19時から予定は空いていますか？
>空いていない場合平日のどこかで時間を合わせられればと考えています

大丈夫です！

> Compassイベントページに掲載するセッション情報について

@naoki-haba  さんに共有済みです！

よろしくおねがいします。

**Comment by naokihaba** [comment]
順番について2番でも3番でもどちらでも可

ラストが空いてればラストでお願いすることで調整しました

**Comment by naokihaba** [comment]
当日の進行スライドのたたきを共有いたします！

[進行スライド](https://www.canva.com/design/DAFFhOVPzEA/eodqfonYAgTV4CmjTgPTCg/view?utm_content=DAFFhOVPzEA&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
