### ISSUE TITLE
新プロダクト開発でNestJSを導入してみた

### ISSUE THREAD

**Issue by kumewata** [nestjs-jp/nestjs-meetup-community-conference-2022-cfp#3]
### Twitter ID (必須)

wataridori_k

### セッションタイトル (必須)

- [X] セッションのタイトルをイシュー件名に最大40文字程度で入力しました

### セッションのアブストラクト (最大250文字) (必須)

サーバーサイドをPython/Djangoで開発してきたチームがNestJSを導入するまでの経緯を紹介しつつ、採用してみて良かったこと・大変だったこと等お話しします🙋‍♂️

キーワード
- NestJSのModule, DI
- Aspidaによるクライアントとの型共有
- 管理画面どう作る？

### 想定受講者の開発対象やロール・役割 (複数選択可) (必須)

Web フロントエンド開発, Web バックエンド / サーバーサイド開発

### セッションのトピック (複数選択可) (必須)

アプリケーションアーキテクチャー, 開発プロセス

### セッションのフォーマット (必須)

スライドを映しながら話す、通常セッション

**Comment by naokihaba** [comment]
[NestJS meetup Online #3](https://nest-jp.connpass.com/event/247927/) へのセッション応募ありがとうございます！

6月27日の抽選後、運営よりご連絡します
運営によるツイートのリツイートや、あるいはご自身での宣伝・所属企業の広報による宣伝など、ぜひぜひソーシャルでのシェアもお願いいたします。

**Comment by odanado** [comment]
@kumewata 
NestJS meetup Online #3 へのセッション応募ありがとうございました！

抽選の結果,登壇が決定しましたのでお知らせします。

今後のやり取りについては引き続きGitHubで行います

早速ですが2点確認がございます

1. 当日のリハーサルについて
当日は19時半開始ですが、19時頃に集まって登壇用のシステムの説明を行いたいと考えています。
19時から予定は空いていますか？
空いていない場合平日のどこかで時間を合わせられればと考えています

2. Compassイベントページに掲載するセッション情報について

イベント当日の1週間前までに以下を共有ください
- 所属企業（任意）
- イベントヘッダーに表示するアイコン画像（任意）
- スライドに表示する企業ロゴ画像（任意）SVGやAIファイル等

イメージは[NestJS meetup Online #2](https://nest-jp.connpass.com/event/244015/) を参照ください

**Comment by kumewata** [comment]
@odanado 
ご連絡ありがとうございます！
1のリハーサルについて、当日19時から参加できます🙆‍♂️
2についても承知いたしました。後ほど共有させていただきます。

**Comment by naokihaba** [comment]
@kumewata 
お疲れ様です！
当日の登壇順についてご希望ございますでしょうか？

1番目については別の登壇者さんのご都合上確定しております

2番目 or 3番目が現在空いております！

**Comment by naokihaba** [comment]
当日の進行スライドのたたきを共有いたします！

[進行スライド](https://www.canva.com/design/DAFFhOVPzEA/eodqfonYAgTV4CmjTgPTCg/view?utm_content=DAFFhOVPzEA&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

**Comment by kumewata** [comment]
@naoki-haba 
お疲れ様です！
では2番目希望でお願いします！
（早めに発表して他の登壇者さんの発表ものんびり聞きたい、程度の希望なので3番目でも大丈夫です🙆‍♂️）

スライドの共有もありがとうございます！

**Comment by naokihaba** [comment]
@kumewata 
ありがとうございます！！
では2番目の登壇をお願いします🙇‍♂️🙇‍♂️

**Comment by kumewata** [comment]
ご確認ありがとうございます！

@naoki-haba @odanado 
またtwitterの方で、セッション情報についてDMさせていただきました。
ご確認のほどよろしくお願いします。

**Comment by naokihaba** [comment]
@kumewata 
DM確認いたしました！！
早速ご共有いただいた内容をスライドに反映させていただきます！

**Comment by naokihaba** [comment]
@kumewata 
反映させていただきました
[イベントページ](https://nest-jp.connpass.com/event/247927/
)

URLは一旦御社のトップページとしてます

[イベントスライド](https://www.canva.com/design/DAFFhOVPzEA/eodqfonYAgTV4CmjTgPTCg/view?utm_content=DAFFhOVPzEA&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

御社のロゴ利用規則に則って配置いたしました

**Comment by kumewata** [comment]
@naoki-haba 早速のご対応ありがとうございます！

**Comment by naokihaba** [comment]
@kumewata 

当日は`streamyard`で配信を行います！
使い方は以下を参照ください🙇‍♂️
https://hackmd.io/@potato4d/SJa6zdubq

リハーサルの時間になりましたら以下リハーサルルームに入室ください！

当日配信ルーム https://streamyard.com/bmvasrjkga
当日リハーサルルーム https://streamyard.com/y8ay3qz24g

**Comment by kumewata** [comment]
@naoki-haba 
承知しました！当日よろしくお願いします！
