### ISSUE TITLE
BtoB Enterprise SaaSでのNestJS選定

### ISSUE THREAD

**Issue by charly24** [nestjs-jp/nestjs-meetup-community-conference-2022-cfp#4]
### Twitter ID (必須)

ryo_nagaoka

### セッションタイトル (必須)

- [X] セッションのタイトルをイシュー件名に最大40文字程度で入力しました

### セッションのアブストラクト (最大250文字) (必須)

Beatrust( http://beatrust.com/ )はBtoB Enterprise領域でサービスを提供するスタートアップです。
創業した2020年時点では今ほど日本でNestJSはメジャーではなかった時期ですが、当時の選定背景や、その後2年運用してどう感じているかについて紹介します。

### 想定受講者の開発対象やロール・役割 (複数選択可) (必須)

Web フロントエンド開発, Web バックエンド / サーバーサイド開発

### セッションのトピック (複数選択可) (必須)

アプリケーションアーキテクチャー

### セッションのフォーマット (必須)

スライドを映しながら話す、通常セッション

**Comment by naokihaba** [comment]
@charly24 
ありがとうございます！！
こちらの内容でイベントページを更新いたしました
あわせて諸連絡と当日の進行スライドをDMにお送りしましたのでご確認の程よろしくお願い致します！

**Comment by naokihaba** [comment]
当日はstreamyardで配信を行います！
使い方は以下を参照ください🙇‍♂️
https://hackmd.io/@potato4d/SJa6zdubq

リハーサルの時間になりましたら以下リハーサルルームに入室ください！

当日配信ルーム https://streamyard.com/bmvasrjkga
当日リハーサルルーム https://streamyard.com/y8ay3qz24g
