### ISSUE TITLE
実践NestJS

### ISSUE THREAD

**Issue by balmychan** [nestjs-jp/nestjs-meetup-community-conference-2022-cfp#5]
### Twitter ID (必須)

balmychan

### 発表見込み時間 (必須)

20

### セッションタイトル (必須)

- [x] セッションのタイトルをイシュー件名に最大40文字程度で入力しました

### セッションのアブストラクト (最大250文字) (必須)

株式会社オロ 新規事業開発チーム 後藤歩と申します。
NestJSは弊社の2つのプロダクトで1年ほど使っています。
（個人的にも1プロダクトで使っており、合計3プロダクトでNestJSを使って開発をしています）

その実例をコードを交えてご紹介できればと思います。

- システム構成
- 認証、認可、フレームワーク、DB、API、バリデーション、キューイング、スケジューリング、マイグレーション、テスト、Swagger、i18nをどのようにやっているかのコードを交えて実例紹介
- フロントエンド（React + Apollo Client）と組み合わせた場合の実例

など
よろしくお願いいたします。

### 想定受講者の開発対象やロール・役割 (複数選択可) (必須)

Web バックエンド / サーバーサイド開発

### セッションのトピック (複数選択可) (必須)

プログラミング, アプリケーションアーキテクチャー

### セッションのフォーマット (必須)

スライドを映しながら話す、通常セッション

**Comment by mic9-haba** [comment]
[NestJS meetup Online #4](https://nest-jp.connpass.com/event/255459/) へのセッションご応募ありがとうございます！

運営によるツイートのリツイートや、あるいはご自身での宣伝・所属企業の広報による宣伝など、ぜひぜひソーシャルでのシェアもお願いいたします🙇‍♂️

企業ロゴ画像・ユーザーアイコン等の掲載について可能であればご共有いただけますと助かります🙇‍♂️
https://nest-jp.connpass.com/event/247927/

**Comment by naokihaba** [comment]
@balmychan 

[NestJS meetup Online #4](https://nest-jp.connpass.com/event/255459/) へのセッションご応募ありがとうございます！

運営によるツイートのリツイートや、あるいはご自身での宣伝・所属企業の広報による宣伝など、ぜひぜひソーシャルでのシェアもお願いいたします🙇‍♂️

企業ロゴ画像・ユーザーアイコン等の掲載について可能であればご共有いただけますと助かります🙇‍♂️
https://nest-jp.connpass.com/event/247927/

**Comment by naokihaba** [comment]
イベントページに掲載いたしますヘッダー画像になります。
アカウント名・企業名の相違・アイコン画像の変更等ご要望があればお伝えください🙇
![20220722 1930_2100](https://user-images.githubusercontent.com/59875779/187041597-b904cd0c-8298-45f7-b961-754f0359997b.png)
