### ISSUE TITLE
NestJS のライフサイクルと TypeORM のコネクションプールの管理について

### ISSUE THREAD

**Issue by lightnet328** [nestjs-jp/nestjs-meetup-community-conference-2022-cfp#6]
### Twitter ID (必須)

lightnet328

### 発表見込み時間 (必須)

20

### セッションタイトル (必須)

- [X] セッションのタイトルをイシュー件名に最大40文字程度で入力しました

### セッションのアブストラクト (最大250文字) (必須)

細かい設定をしなくても NestJS は良い感じに動いてくれるので NestJS を実際の開発に使っている方でも NestJS のライフサイクルや TypeORM のコネクションプールの挙動について上手く理解している方は多くないのではないでしょうか。
今回は「NestJS のライフサイクルと TypeORM のコネクションプールの管理について」というテーマでプロダクション運用に耐えうる NestJS アプリケーションをデプロイするために必要な NestJS や TypeORM の仕組みについて話したいと思います。

### 想定受講者の開発対象やロール・役割 (複数選択可) (必須)

Web バックエンド / サーバーサイド開発

### セッションのトピック (複数選択可) (必須)

アプリケーションアーキテクチャー

### セッションのフォーマット (必須)

スライドを映しながら話す、通常セッション

**Comment by naokihaba** [comment]
[NestJS meetup Online #4](https://nest-jp.connpass.com/event/255459/) へのセッションご応募ありがとうございます！

運営によるツイートのリツイートや、あるいはご自身での宣伝・所属企業の広報による宣伝など、ぜひぜひソーシャルでのシェアもお願いいたします🙇‍♂️

企業ロゴ画像・ユーザーアイコン等の掲載について可能であればご共有いただけますと助かります🙇‍♂️
https://nest-jp.connpass.com/event/247927/

**Comment by naokihaba** [comment]
イベントページに掲載いたしますヘッダー画像になります。
アカウント名・企業名の相違・アイコン画像の変更等ご要望があればお伝えください🙇
![20220722 1930_2100](https://user-images.githubusercontent.com/59875779/187041625-b4d2703f-d04b-45ca-bb3d-783b5f5bd5fc.png)
