### ISSUE TITLE
@nestjs/bull の活用について

### ISSUE THREAD

**Issue by odanado** [nestjs-jp/nestjs-meetup-community-conference-2022-cfp#7]
### Twitter ID (必須)

odan3240

### 発表見込み時間 (必須)

15分

### セッションタイトル (必須)

- [X] セッションのタイトルをイシュー件名に最大40文字程度で入力しました

### セッションのアブストラクト (最大250文字) (必須)

NestJS を用いたバックエンドで非同期処理を実装する場合 https://github.com/nestjs/bull が1つの候補として挙がります
サービスを実際に運用する上での `@nestjs/bull` の使い方についてご紹介します

### 想定受講者の開発対象やロール・役割 (複数選択可) (必須)

Web バックエンド / サーバーサイド開発

### セッションのトピック (複数選択可) (必須)

プログラミング

### セッションのフォーマット (必須)

スライドを映しながら話す、通常セッション

**Comment by naokihaba** [comment]
イベントページにセッション情報を反映いたしました
あわせてイベントバナー・配信用スライドについても添付させていただきます
表記にお間違いがないかご確認の程よろしくお願いいたします

https://nest-jp.connpass.com/event/255459/

イベントバナー画像
![20220722 1930_2100](https://user-images.githubusercontent.com/59875779/191039275-9b06334b-48f9-4dcc-823f-11d8a92c4fb5.png)


配信スライド
https://www.canva.com/design/DAFLvgIL8qY/5v1XZ4iPBdlopIUsuq1dvg/view?utm_content=DAFLvgIL8qY&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink

**Comment by odanado** [comment]
@naoki-haba ありがとうございます
問題ないです！
